from pathlib import Path
import json

root = Path(__file__).resolve().parents[2]
data = json.loads((root / 'guanyu-html-builder' / 'demo' / 'ppt-content.json').read_text(encoding='utf-8'))
payload = json.dumps(data['slides'], ensure_ascii=False).replace('</', '<\\/')
html = r'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GUANYU / Editable HTML Presentation</title><style>
*{box-sizing:border-box}body{margin:0;background:#171717;color:#fff;font-family:Arial,sans-serif;overflow:hidden}.stage{position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);width:min(100vw,calc(100vh * 16 / 9));height:min(100vh,calc(100vw * 9 / 16));aspect-ratio:16/9;background:#000}.slide{position:absolute;inset:0;opacity:0;visibility:hidden;transition:opacity .35s}.slide.active{opacity:1;visibility:visible}.slide img{width:100%;height:100%;object-fit:contain}.bar{position:fixed;left:0;right:0;bottom:0;height:4px;background:#444}.bar i{display:block;height:100%;background:#fff;width:0}.counter{position:fixed;right:18px;bottom:14px;font:11px monospace;color:#aaa}.hint{position:fixed;left:18px;bottom:14px;font:11px monospace;color:#777}.edit{position:fixed;right:0;top:0;width:min(420px,92vw);height:100vh;background:#f5f5f3;color:#000;padding:22px;transform:translateX(100%);transition:transform .25s;overflow:auto;z-index:4}.edit.open{transform:translateX(0)}.edit h1{font-size:20px;margin:0 0 8px}.edit p{font-size:12px;color:#666;line-height:1.5}.edit textarea{width:100%;min-height:88px;margin:8px 0 16px;padding:10px;border:1px solid #bbb;background:#fff;font:14px/1.5 Arial;resize:vertical}.edit button{border:1px solid #000;background:#000;color:#fff;padding:10px 13px;margin:0 6px 8px 0;cursor:pointer}.edit button.light{background:#fff;color:#000}.close{float:right;background:none!important;color:#000!important;border:0!important;font-size:20px}.notice{padding:10px;background:#e8e8e5;font-size:12px;line-height:1.5;margin:12px 0}.edit-overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,.35);z-index:3}.edit.open~.edit-overlay{display:block}@media(prefers-reduced-motion:reduce){.slide,.edit{transition:none}}
</style></head><body><main class="stage" aria-label="观宇芯算可编辑 HTML 演示"><div id="slides"></div></main><div class="bar"><i id="progress"></i></div><div class="counter" id="counter"></div><div class="hint">← → / SPACE 翻页 · E 编辑 · HOME / END</div><aside class="edit" id="editor"><button class="close" id="close">×</button><h1>GUANYU 内容编辑</h1><p id="pageLabel"></p><div class="notice">编辑内容会保存到当前浏览器。视觉页面仍以新版校准 PPT 为参考，文本修改会作为内容数据保存。</div><div id="fields"></div><button id="save">保存当前页</button><button class="light" id="reset">恢复原始内容</button><button class="light" id="export">导出 JSON</button></aside><div class="edit-overlay" id="overlay"></div><script>
const source=__PAYLOAD__;const slides=document.getElementById('slides');const storeKey='guanyu-html-ppt-content-v1';let data=JSON.parse(localStorage.getItem(storeKey)||'null')||source.map(x=>({slide:x.slide,texts:[...x.texts]}));let current=0;for(let i=1;i<=27;i++){const s=document.createElement('section');s.className='slide'+(i===1?' active':'');const img=document.createElement('img');img.src=`ppt-slides/slide-${i}.png`;img.alt=`观宇芯算 PPT 第 ${i} 页`;s.appendChild(img);slides.appendChild(s)}const pages=[...document.querySelectorAll('.slide')];function show(n){current=Math.max(0,Math.min(pages.length-1,n));pages.forEach((x,i)=>x.classList.toggle('active',i===current));counter.textContent=String(current+1).padStart(2,'0')+' / '+pages.length;progress.style.width=((current+1)/pages.length*100)+'%';if(editor.classList.contains('open'))renderEditor()}function renderEditor(){pageLabel.textContent=`第 ${current+1} 页 · ${data[current].texts.length} 个文本对象`;fields.innerHTML='';data[current].texts.forEach((text,i)=>{const label=document.createElement('label');label.textContent=`文本对象 ${i+1}`;const area=document.createElement('textarea');area.value=text;area.dataset.index=i;area.addEventListener('input',e=>data[current].texts[Number(e.target.dataset.index)]=e.target.value);fields.append(label,area)})}function toggle(){editor.classList.toggle('open');if(editor.classList.contains('open'))renderEditor()}document.addEventListener('keydown',e=>{if(e.key==='e'||e.key==='E'){toggle();return}if(['ArrowRight',' ','PageDown'].includes(e.key)){e.preventDefault();show(current+1)}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();show(current-1)}else if(e.key==='Home')show(0);else if(e.key==='End')show(pages.length-1)});close.onclick=toggle;overlay.onclick=toggle;save.onclick=()=>{localStorage.setItem(storeKey,JSON.stringify(data));alert('当前内容已保存到浏览器')};reset.onclick=()=>{data=source.map(x=>({slide:x.slide,texts:[...x.texts]}));localStorage.removeItem(storeKey);renderEditor()};export.onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({slides:data},null,2)],{type:'application/json'}));a.download='guanyu-ppt-content-edited.json';a.click();URL.revokeObjectURL(a.href)};show(0);
</script></body></html>'''.replace('__PAYLOAD__', payload)
output = root / 'guanyu-html-builder' / 'demo' / 'ppt-editable.html'
output.write_text(html, encoding='utf-8')
print(output)
