from pathlib import Path
import json

root = Path(__file__).resolve().parents[2]
layout = json.loads((root/'guanyu-html-builder/demo/ppt-layout.json').read_text(encoding='utf-8'))['slides']
payload = json.dumps(layout, ensure_ascii=False).replace('</','<\\/')
html = r'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GUANYU / Editable Presentation</title><style>*{box-sizing:border-box}body{margin:0;background:#171717;color:#111;font-family:Arial,sans-serif;overflow:hidden}.stage{position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);width:min(100vw,calc(100vh * 16 / 9));height:min(100vh,calc(100vw * 9 / 16));aspect-ratio:16/9;background:#fff;overflow:hidden}.slide{position:absolute;inset:0;opacity:0;visibility:hidden}.slide.active{opacity:1;visibility:visible}.slide img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain}.layer{display:none;position:absolute;inset:0}.editing .layer{display:block}.text{position:absolute;overflow:hidden;white-space:pre-wrap;line-height:1.15;outline:0;pointer-events:none}.editing .text{pointer-events:auto;cursor:text;outline:1px dashed #777;background:rgba(255,255,255,.18)}.bar{position:fixed;left:0;right:0;bottom:0;height:4px;background:#444}.bar i{display:block;height:100%;background:#fff;width:0}.counter{position:fixed;right:18px;bottom:14px;font:11px monospace;color:#aaa}.hint{position:fixed;left:18px;bottom:14px;font:11px monospace;color:#777}.editing .hint{color:#fff}.edit{position:fixed;right:0;top:0;width:min(360px,92vw);height:100vh;background:#f5f5f3;padding:18px;transform:translateX(100%);transition:transform .2s;z-index:4;overflow:auto}.edit.open{transform:translateX(0)}.edit h1{font-size:18px}.edit button{padding:9px 12px;background:#000;color:#fff;border:0;margin:0 5px 8px 0}.edit .light{background:#fff;color:#000;border:1px solid #000}.edit p{font-size:12px;color:#666}.item{padding:10px 0;border-top:1px solid #ccc}.item label{font-size:11px;color:#666}.item textarea{width:100%;height:58px;margin-top:5px;font:12px Arial}.close{float:right;background:none!important;color:#000!important;font-size:20px}.overlay{display:none;position:fixed;inset:0;background:#0005;z-index:3}.edit.open~.overlay{display:block}@media(prefers-reduced-motion:reduce){.edit{transition:none}}</style></head><body><main class="stage"><div id="slides"></div></main><aside class="edit" id="editor"><button class="close" id="close">脳</button><h1>GUANYU 鏂囨湰缂栬緫</h1><p id="label"></p><button id="save">淇濆瓨</button><button class="light" id="reset">鎭㈠</button><button class="light" id="export">瀵煎嚭 JSON</button><div id="items"></div></aside><div class="overlay" id="overlay"></div><div class="bar"><i id="progress"></i></div><div class="counter" id="counter"></div><div class="hint">鈫?鈫?/ SPACE 缈婚〉 路 E 缂栬緫 路 HOME / END</div><script>
const exportBtn=document.getElementById('export'),source=__PAYLOAD__,key='guanyu-ppt-layout-v2';let data=JSON.parse(localStorage.getItem(key)||'null')||source.map(s=>({slide:s.slide,items:s.items.map(x=>({...x}))}));let current=0;const root=document.querySelector('#slides');data.forEach((page,pi)=>{const s=document.createElement('section');s.className='slide'+(!pi?' active':'');const img=document.createElement('img');img.src=`ppt-slides/slide-${pi+1}.png`;s.append(img);const layer=document.createElement('div');layer.className='layer';page.items.forEach((item,ii)=>{const el=document.createElement('div');el.className='text';el.contentEditable='true';el.dataset.i=ii;el.textContent=item.text;Object.assign(el.style,{left:item.x/1280*100+'%',top:item.y/720*100+'%',width:item.w/1280*100+'%',height:item.h/720*100+'%',fontFamily:item.font,fontSize:item.size/1280*100+'vw',color:item.color});el.oninput=()=>item.text=el.innerText;layer.append(el)});s.append(layer);root.append(s)});const pages=[...document.querySelectorAll('.slide')];function show(n){current=Math.max(0,Math.min(pages.length-1,n));pages.forEach((s,i)=>s.classList.toggle('active',i===current));counter.textContent=String(current+1).padStart(2,'0')+' / '+pages.length;progress.style.width=((current+1)/pages.length*100)+'%'}function edit(){document.body.classList.toggle('editing');editor.classList.toggle('open');if(editor.classList.contains('open'))render()}function render(){label.textContent=`绗?${current+1} 椤?路 ${data[current].items.length} 涓枃鏈`;items.innerHTML='';data[current].items.forEach((x,i)=>{const box=document.createElement('div');box.className='item';box.innerHTML=`<label>${i+1} 路 ${x.font} 路 ${Math.round(x.size)}px</label>`;const ta=document.createElement('textarea');ta.value=x.text;ta.oninput=()=>{x.text=ta.value;const live=pages[current].querySelectorAll('.text')[i];if(live)live.textContent=ta.value};box.append(ta);items.append(box)})}document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='e'){edit();return}if(['ArrowRight',' ','PageDown'].includes(e.key)){e.preventDefault();show(current+1)}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();show(current-1)}else if(e.key==='Home')show(0);else if(e.key==='End')show(pages.length-1)});close.onclick=edit;overlay.onclick=edit;save.onclick=()=>localStorage.setItem(key,JSON.stringify(data));reset.onclick=()=>{localStorage.removeItem(key);location.reload()};exportBtn.onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({slides:data},null,2)],{type:'application/json'}));a.download='guanyu-ppt-layout-edited.json';a.click();URL.revokeObjectURL(a.href)};show(0);
</script></body></html>'''.replace('__PAYLOAD__',payload)
(root/'guanyu-html-builder/demo/ppt-editable-overlay.html').write_text(html,encoding='utf-8')
print('built overlay editor')

